### ISSUE TITLE
add 66.249.84.0/23

### ISSUE THREAD

**Issue by zhaoshengyun** [pksh71/gmail-bot-email-open-click-ip-ranges#1]
66.249.84.0/23

**Comment by pksh71** [comment]
No This Range does not belong to BOT CLICK & OPEN Proxy, Its is used by the Gmail Image proxy Server, to record genuine open by users and protect users' Identity gmail pass these open email request to proxy servers.

**Comment by zhaoshengyun** [comment]
I see，forgive my ignorance ：）
